// Nextjs Imports
import Head from "next/head";
// import Image from "next/image";
// import {Inter} from "next/font/google";

// Style imports
// import styles from "@/styles/Home.module.css";

// ChakraUI Imports
import {Container} from "@chakra-ui/react";

// Component Imports
import Timer from "../../components/Timer";

// const inter = Inter({subsets: ["latin"]});

export default function Home() {
  return (
    <>
      <Head>
        <title>Pomodoro Timer App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <>
        <Container
          // bgImage="url('/images/waves.jpg')"
          // bgSize="cover"
          maxW="full"
          centerContent
          h="100vh"
          justifyContent="center"
        >
          <video
            autoPlay
            muted
            loop
            className="video-bg"
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              height: "100%",
              objectFit: "cover",
              zIndex: -1
            }}
          >
            <source src="/images/fireplace.mp4" type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          <Timer
            workMinutes={25}
            shortBreakMinutes={5}
          />
        </Container>
      </>
    </>
  );
}
